print(repr("café"))
print(repr("中文"))
print(repr("\U0001F600"))
print(repr("a​b"))
print(repr("x y"))
print(repr("­"))
print(repr(""))
print(repr(" "))
print(repr("\U000E0001"))
print(repr("tab\tnl\n"))
print(repr("é"))
print(["café", "​"])
print({"k": "café"})
print(ascii("café"), ascii("中文"))
print(int("１２"), int("١٢"), int("１_２"))
print(int("１２", 16), int("١٢", 8), int("１２", 0))
print(float("１２"), float("１.５"), float("１e２"))
print(len("café"), len("\U0001F600"), len("中文"))
print(str(12), str("café"))
