print(str.maketrans("ab", "xy"))
print(str.maketrans("ab", "xy", "c"))
print(str.maketrans({"a": "X"}))
print(str.maketrans({97: "X"}))
print(str.maketrans({"a": None}))
print(str.maketrans({}))
print(str.maketrans("日", "X"))

print("abc".translate(str.maketrans("ab", "xy")))
print("abcd".translate(str.maketrans("ab", "xy", "c")))
print("abc".translate(str.maketrans({"a": "Z"})))

print("abc".maketrans("a", "b"))
print({}.fromkeys([1, 2]))
print(b"abc".fromhex("6162"))

print(len(bytes.maketrans(b"ab", b"xy")))
print(b"abc".translate(bytes.maketrans(b"ab", b"xy")))
print(b"abcd".translate(bytes.maketrans(b"ab", b"xy"), b"c"))
print(b"".maketrans(b"a", b"b")[97])

print(dict.fromkeys("abc"))
print(dict.fromkeys([1, 2], 0))
print(dict.fromkeys([]))
print(dict.fromkeys([1, 1]))
print(dict.fromkeys("aab", 1))
print(dict.fromkeys((1, 2), "v"))

print(bytes.fromhex("616263"))
print(bytes.fromhex("61 62"))
print(bytes.fromhex("61  62"))
print(bytes.fromhex("6162 "))
print(bytes.fromhex(" 6162"))
print(bytes.fromhex("AbCd"))
print(bytes.fromhex("61\t62"))
print(bytes.fromhex("61\n62"))
print(bytes.fromhex(b"6162"))
print(bytes.fromhex(""))
