print(hash(0), hash(1), hash(-1), hash(-2), hash(7), hash(2 ** 61), hash(2 ** 62 + 5))
print(hash(True), hash(False), hash(None))
print(hash(0.0), hash(-0.0), hash(1.0), hash(3.5), hash(-2.5), hash(1e16), hash(1e-308), hash(1e308))
print(hash(float("inf")), hash(float("-inf")))
print(hash(1) == hash(1.0), hash(1) == hash(True), hash(-1) == hash(-2), hash(0) == hash(-0.0))
print(hash(""), hash("a"), hash("abc"), hash("hello world"), hash("héllo"), hash("€"), hash("\U0001F600"))
print(hash(b""), hash(b"a"), hash(b"abc"), hash(b"\xe4"))
print(hash(()), hash((1, 2)), hash((1, 2, 3)), hash(("a", "b")), hash((1, (2, 3))), hash((None, 3.5)))
print(hash(range(3)), hash(range(0, 10, 3)), hash(range(3, 0, -1)), hash(range(0)), hash(range(5, 5)))
print(hash("a") == hash(b"a"), hash(1.0) == 1, hash("abc") == hash("abc"))
print(hash("a") != hash("b"), hash(frozenset([1, 2])) == hash(frozenset([2, 1])))
print(hash(frozenset([1, 2, 3])) == hash(frozenset([3, 1, 2])), hash(frozenset()) == hash(frozenset()))
