print(isinstance(1, int), isinstance(True, int), isinstance(1, bool), isinstance(1.0, int), isinstance("x", str), isinstance([], list))
print(isinstance(1, (str, int)), isinstance(1, (str, float)), isinstance(1, ()), isinstance(int, type), isinstance([], (list, tuple)))
print(isinstance((), tuple), isinstance({}, dict), isinstance(set(), set), isinstance(b"x", bytes), isinstance(range(3), range), isinstance(3.0, float))
print(callable(print), callable(len), callable(int), callable(abs), callable(5), callable("x"), callable([]), callable(type))
print(type(id(1)), id(1) == id(1), id("a") == id("a"))
x = [1, 2]
print(id(x) == id(x), id(x) == id([1, 2]))
print(ord("a"), ord("A"), ord("0"), ord(" "), ord("é"), ord("€"), ord("\U0001F600"), ord("\n"), ord(b"a"), ord(b"\xff"))
print(chr(97), chr(65), chr(233), chr(8364), chr(128512), chr(0), chr(1114111), chr(True))
print(ord(chr(233)), chr(ord("Z")), ord(chr(128512)))
print(bin(0), bin(5), bin(-5), bin(255), bin(True), bin(1024))
print(oct(0), oct(8), oct(-8), oct(64), oct(True))
print(hex(0), hex(255), hex(-255), hex(16), hex(True))
print(format(255, "x"), format(3.14159, ".2f"), format(42, "05d"), format("hi", ">5"), format(255, "#x"), format(1000000, ","))
print(format(42), format("x"), format(3.5), format(True), format([1, 2]), format(3.14159, ".0f"))
print(ascii("abc"), ascii("café"), ascii("\U0001F600"), ascii([1, "aé"]), ascii("'\""))
print(ascii(42), ascii(3.5), ascii(None), ascii(b"x\xff"), ascii({"ké": "v€"}), ascii(("aé",)))
print(f"{'café'!a}", f"{42!a}", f"{'x'!r}", f"{'y'!s}")
print(bin(10) + oct(10) + hex(10), sorted([hex(n) for n in [15, 255, 16]]))
