print(type(1))
print(type(1.5))
print(type("a"))
print(type(True))
print(type([]))
print(type((1,)))
print(type({}))
print(type({1, 2}))
print(type(b"x"))
print(type(None))
print(type(int))
print(type(type))
print(type(1) is int)
print(type("a") is str)
print(type(True) is bool)
print(type([]) is list)
print(type(1) is str)
print(type(1) == int)
print(int("42"))
print(str(255))
print(bool(0))
print(bool(5))
print(bool([]))
print(bool("x"))
print(int)
print(str)
print(dict)
