print(ValueError, TypeError, KeyError, IndexError, StopIteration)
print(issubclass(ValueError, Exception), issubclass(ValueError, BaseException), issubclass(Exception, ValueError))
print(issubclass(KeyError, LookupError), issubclass(LookupError, Exception), issubclass(RecursionError, RuntimeError))
print(issubclass(TypeError, Exception), issubclass(OSError, Exception), issubclass(FileNotFoundError, OSError))
print(issubclass(UserWarning, Warning), issubclass(Warning, Exception), issubclass(Warning, BaseException))
e = ValueError("boom")
print(e, repr(e), str(e), type(e), type(e) is ValueError)
print(isinstance(e, ValueError), isinstance(e, Exception), isinstance(e, TypeError), isinstance(e, BaseException))
print(repr(KeyError("k")), str(KeyError("k")), repr(ValueError()), str(ValueError()))
print(repr(ValueError(1, 2)), str(ValueError(1, 2)))
print(callable(ValueError), callable(e), isinstance(ValueError, type), issubclass(type, object))
print(type(ValueError("x")) is ValueError, e == e, ValueError("x") == ValueError("x"))
print(isinstance(True, int), isinstance(ValueError, object), issubclass(bool, int))
print(EnvironmentError is OSError, IOError is OSError, issubclass(WindowsError, OSError))
print(issubclass(PythonFinalizationError, RuntimeError), issubclass(ExceptionGroup, Exception))
