print("{} {}".format(1, 2))
print("{1} {0}".format(1, 2))
print("{0}{0}".format(1))
print("{}".format(1, 2))
print("{}".format(1, k=2))
print(repr("".format(1)))
print("{k}".format(k=5))
print("{a}-{b}".format(a=1, b=2))

print("{0[1]}".format([9, 8]))
print("{0[a]}".format({"a": 1}))
print("{0[0]}".format("xy"))
print("{a[0]}".format(a=[1, 2]))
print("{0[01]}".format([1, 2]))
print("{0[a b]}".format({"a b": 1}))
print("{0[1][0]}".format([9, [7, 6]]))

print("{{}}".format())
print("{{{}}}".format(1))
print("}}".format())
print("{{".format())
print("a{{b}}c".format())

print("{!r}".format("a"))
print("{!s}".format("a"))
print("{!a}".format("café"))
print("{!r:>8}".format("a"))
print("{:>5}".format("a"))
print("{:05.2f}".format(3.14159))
print("{:,}".format(1234567))
print("{:+d} {:x} {:o} {:b}".format(5, 255, 8, 5))
print("{:^7}".format("ab"))

print("{:{}}".format(7, ">5"))
print("{:>{}}".format(7, 5))
print("{:{}{}}".format(7, ">", 5))
print("{0:{1}}".format(7, ">5"))
print("{:{w}}".format(7, w=">5"))
print("{!r:{}}".format("a", ">5"))

print("{k}".format_map({"k": 1}))
print("{k}-{j}".format_map({"k": 1, "j": 2}))
print("{k}".format_map({"k": 1, "z": 2}))
print("{k[0]}".format_map({"k": [5, 6]}))
print("{k:>4}".format_map({"k": "x"}))

print("{}".format(None))
print("{}".format([1, 2]))
print("{}".format({"a": 1}))
print("{} {}".format(True, 1.5))
print("{}".format("日"))
