print(True)
print(False)
print(True + True)
print(True + 1)
print(False * 5)
print(1 == 1)
print(1 != 1)
print(2 < 3)
print(5 > 10)
print(3 <= 3)
print(not 0)
print(not "")
print(not "x")
print(True and False)
print(False or 7)
print(1 in [1, 2, 3])
print(9 in [1, 2, 3])
print(True == 1)
print(False == 0)
print(True < 5)
print([10, 20, 30][True])
print((5, 6, 7)[False])
print("abcdef"[True:4])
print(int(True))
print(int(False))
print(float(True) == 1.0)
print(-True)
print(+False)
print(1 in b"\x01\x02")
print(True in b"\x01\x02")
xs = [0, 0]
xs[True] = 9
print(xs[1])
