name = "world"
x = 42
pi = 3.14159
print(f"hello {name}")
print(f"{x} and {name}")
print(f"{x:5}")
print(f"{x:<5}|")
print(f"{x:>5}|")
print(f"{x:^6}|")
print(f"{x:05}")
print(f"{x:+}")
print(f"{-x:+}")
print(f"{1234567:,}")
print(f"{255:x}")
print(f"{255:#x}")
print(f"{255:08b}")
print(f"{10:o}")
print(f"{pi:.2f}")
print(f"{pi:10.3f}")
print(f"{pi:<10.2f}|")
print(f"{pi:.0f}")
print(f"{1000000.0:.2e}")
print(f"{0.25:.1%}")
print(f"{pi}")
print(f"{name!r}")
print(f"{name:>8}")
print(f"{name:.3}")
print(f"{name:*^9}")
print(f"result={x*2}")
print(f"{x} {pi:.1f} {name!r}")
print(f"{{literal braces}}")
w = 8
print(f"{x:{w}}")
