print([1, 2] + [3, 4])
print((1, 2) + (3, 4))
print("ab" + "cd")
print("ab" * 3)
print(3 * "ab")
print([0] * 4)
print([1, 2] * 2)
print((7,) * 3)
print("x" * 0)
print([9] * 0)
print(b"ab" + b"cd")
print(b"ab" * 2)
print("ab" * -1)
print([1] * -2)
