print("abc".translate({97: "Z"}))
print("abc".translate({97: None}))
print("abc".translate({97: 98}))
print("abc".translate({97: "XY"}))
print("abc".translate({}))
print("abc".translate({97: ""}))
print("abcabc".translate({97: "Z", 98: None, 99: 100}))
print("日x日".translate({0x65e5: "Y"}))
print("café".translate({0xe9: "e"}))
print("abc".translate({97: 0x65e5}))
print(repr("".translate({97: "Z"})))

identity = bytes(range(256))
print(b"abc".translate(identity))
print(b"abc".translate(None))
print(b"abcd".translate(None, b"c"))
print(b"abcd".translate(None, delete=b"c"))
print(b"abcd".translate(identity, b"bd"))

swapped = bytes([120 if i == 97 else i for i in range(256)])
print(b"abcabc".translate(swapped))
print(b"abcabc".translate(swapped, b"c"))
print(b"".translate(identity))
print(b"abc".translate(identity, b""))
